import React from "react";
import { Layout } from "@/components/Layout";
import { useSeo } from "@/lib/seo";

export default function Terms() {
  useSeo({
    title: "Terms of Service | Tax For Freelancers",
    description: "Terms of Service and usage conditions for the Tax For Freelancers calculator."
  });

  return (
    <Layout title="Terms of Service" description="Last updated: April 29, 2026">
      <h2>1. Acceptance of Terms</h2>
      <p>
        By accessing and using Tax For Freelancers (the "Service"), you accept and agree to be bound by the terms and provision of this agreement. In addition, when using this Service, you shall be subject to any posted guidelines or rules applicable to such services. Any participation in this Service will constitute acceptance of this agreement. If you do not agree to abide by the above, please do not use this Service.
      </p>

      <h2>2. Use of the Calculator</h2>
      <p>
        The Service provides a tool to estimate potential tax liabilities and net income based on user inputs. It is intended solely for educational and informational purposes. You are responsible for ensuring the inputs you provide are accurate to the best of your knowledge if you wish to receive a useful estimate.
      </p>

      <h2>3. Accuracy and Limitations</h2>
      <p>
        <strong>Not Tax Advice:</strong> The information provided by the Service does not constitute financial, investment, legal, or tax advice. The calculator uses generalized formulas and standard IRS data for the 2026 tax year, but it cannot account for your complete financial situation, state/local taxes, or specific deductions.
      </p>
      <p>
        We strongly recommend that you seek the advice of a certified public accountant (CPA) or qualified tax professional before making any financial decisions or filing your taxes. The estimates provided are just that—estimates—and the actual amount you owe to any tax authority may differ materially.
      </p>

      <h2>4. Intellectual Property</h2>
      <p>
        The Service and its original content, features, and functionality are owned by the operator and are protected by international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws.
      </p>

      <h2>5. No Warranty</h2>
      <p>
        This Service is provided "as is" and "as available" without any warranty or representations, expressed or implied. We make no representations or warranties in relation to the completeness or accuracy of the information generated by the calculator.
      </p>

      <h2>6. Limitation of Liability</h2>
      <p>
        In no event shall the operator, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service, or reliance on any estimates produced by the Service.
      </p>

      <h2>7. Changes to These Terms</h2>
      <p>
        We reserve the right, at our sole discretion, to modify or replace these Terms at any time. What constitutes a material change will be determined at our sole discretion. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms.
      </p>

      <h2>8. Governing Law</h2>
      <p>
        These Terms shall be governed and construed in accordance with the laws of the operator's home jurisdiction (Pakistan), without regard to its conflict of law provisions.
      </p>

      <h2>9. Contact</h2>
      <p>
        If you have any questions about these Terms, please contact us via the Contact page.
      </p>
    </Layout>
  );
}
